package com.nemonotfound.nemos.campfires.datagen;

import com.nemonotfound.nemos.campfires.world.level.block.NemosCampfiresBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.tags.BlockTags;
import org.jspecify.annotations.NonNull;

import java.util.concurrent.CompletableFuture;

public class BlockTagProvider extends FabricTagsProvider.BlockTagsProvider {

    public BlockTagProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void addTags(HolderLookup.@NonNull Provider wrapperLookup) {
        valueLookupBuilder(BlockTags.MINEABLE_WITH_AXE)
                .add(NemosCampfiresBlocks.ACACIA_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_QUARTZ_CAMPFIRE);

        valueLookupBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(NemosCampfiresBlocks.COBBLESTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_QUARTZ_CAMPFIRE);

        valueLookupBuilder(BlockTags.CAMPFIRES)
                .add(NemosCampfiresBlocks.ACACIA_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_SOUL_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_COPPER_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_REDSTONE_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_LAPIS_CAMPFIRE)
                .add(NemosCampfiresBlocks.ACACIA_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.BIRCH_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.CHERRY_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.PALE_OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.CRIMSON_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.DARK_OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.JUNGLE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.MANGROVE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.OAK_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.SPRUCE_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.WARPED_QUARTZ_CAMPFIRE)
                .add(NemosCampfiresBlocks.COBBLESTONE_QUARTZ_CAMPFIRE);
    }
}
