package com.nemonotfound.nemos.campfires.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.core.HolderLookup;
import org.jspecify.annotations.NonNull;

import java.util.concurrent.CompletableFuture;

import static com.nemonotfound.nemos.campfires.reference.CampfiresBlockItemIds.*;
import static net.minecraft.tags.BlockTags.*;

public class BlockTagProvider extends FabricTagsProvider.BlockTagsProvider {

    public BlockTagProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void addTags(HolderLookup.@NonNull Provider wrapperLookup) {
        this.tag(MINEABLE_WITH_AXE)
                .add(ACACIA_CAMPFIRE.block())
                .add(BIRCH_CAMPFIRE.block())
                .add(CHERRY_CAMPFIRE.block())
                .add(PALE_OAK_CAMPFIRE.block())
                .add(CRIMSON_CAMPFIRE.block())
                .add(DARK_OAK_CAMPFIRE.block())
                .add(JUNGLE_CAMPFIRE.block())
                .add(MANGROVE_CAMPFIRE.block())
                .add(SPRUCE_CAMPFIRE.block())
                .add(WARPED_CAMPFIRE.block())
                .add(ACACIA_SOUL_CAMPFIRE.block())
                .add(BIRCH_SOUL_CAMPFIRE.block())
                .add(CHERRY_SOUL_CAMPFIRE.block())
                .add(PALE_OAK_SOUL_CAMPFIRE.block())
                .add(CRIMSON_SOUL_CAMPFIRE.block())
                .add(DARK_OAK_SOUL_CAMPFIRE.block())
                .add(JUNGLE_SOUL_CAMPFIRE.block())
                .add(MANGROVE_SOUL_CAMPFIRE.block())
                .add(SPRUCE_SOUL_CAMPFIRE.block())
                .add(WARPED_SOUL_CAMPFIRE.block())
                .add(ACACIA_COPPER_CAMPFIRE.block())
                .add(BIRCH_COPPER_CAMPFIRE.block())
                .add(CHERRY_COPPER_CAMPFIRE.block())
                .add(PALE_OAK_COPPER_CAMPFIRE.block())
                .add(CRIMSON_COPPER_CAMPFIRE.block())
                .add(DARK_OAK_COPPER_CAMPFIRE.block())
                .add(JUNGLE_COPPER_CAMPFIRE.block())
                .add(MANGROVE_COPPER_CAMPFIRE.block())
                .add(OAK_COPPER_CAMPFIRE.block())
                .add(SPRUCE_COPPER_CAMPFIRE.block())
                .add(WARPED_COPPER_CAMPFIRE.block())
                .add(ACACIA_REDSTONE_CAMPFIRE.block())
                .add(BIRCH_REDSTONE_CAMPFIRE.block())
                .add(CHERRY_REDSTONE_CAMPFIRE.block())
                .add(PALE_OAK_REDSTONE_CAMPFIRE.block())
                .add(CRIMSON_REDSTONE_CAMPFIRE.block())
                .add(DARK_OAK_REDSTONE_CAMPFIRE.block())
                .add(JUNGLE_REDSTONE_CAMPFIRE.block())
                .add(MANGROVE_REDSTONE_CAMPFIRE.block())
                .add(OAK_REDSTONE_CAMPFIRE.block())
                .add(SPRUCE_REDSTONE_CAMPFIRE.block())
                .add(WARPED_REDSTONE_CAMPFIRE.block())
                .add(ACACIA_LAPIS_CAMPFIRE.block())
                .add(BIRCH_LAPIS_CAMPFIRE.block())
                .add(CHERRY_LAPIS_CAMPFIRE.block())
                .add(PALE_OAK_LAPIS_CAMPFIRE.block())
                .add(CRIMSON_LAPIS_CAMPFIRE.block())
                .add(DARK_OAK_LAPIS_CAMPFIRE.block())
                .add(JUNGLE_LAPIS_CAMPFIRE.block())
                .add(MANGROVE_LAPIS_CAMPFIRE.block())
                .add(OAK_LAPIS_CAMPFIRE.block())
                .add(SPRUCE_LAPIS_CAMPFIRE.block())
                .add(WARPED_LAPIS_CAMPFIRE.block())
                .add(ACACIA_QUARTZ_CAMPFIRE.block())
                .add(BIRCH_QUARTZ_CAMPFIRE.block())
                .add(CHERRY_QUARTZ_CAMPFIRE.block())
                .add(PALE_OAK_QUARTZ_CAMPFIRE.block())
                .add(CRIMSON_QUARTZ_CAMPFIRE.block())
                .add(DARK_OAK_QUARTZ_CAMPFIRE.block())
                .add(JUNGLE_QUARTZ_CAMPFIRE.block())
                .add(MANGROVE_QUARTZ_CAMPFIRE.block())
                .add(OAK_QUARTZ_CAMPFIRE.block())
                .add(SPRUCE_QUARTZ_CAMPFIRE.block())
                .add(WARPED_QUARTZ_CAMPFIRE.block());

        this.tag(MINEABLE_WITH_PICKAXE)
                .add(COBBLESTONE_CAMPFIRE.block())
                .add(COBBLESTONE_SOUL_CAMPFIRE.block())
                .add(COBBLESTONE_COPPER_CAMPFIRE.block())
                .add(COBBLESTONE_REDSTONE_CAMPFIRE.block())
                .add(COBBLESTONE_LAPIS_CAMPFIRE.block())
                .add(COBBLESTONE_QUARTZ_CAMPFIRE.block());

        this.tag(CAMPFIRES)
                .add(ACACIA_CAMPFIRE.block())
                .add(BIRCH_CAMPFIRE.block())
                .add(CHERRY_CAMPFIRE.block())
                .add(PALE_OAK_CAMPFIRE.block())
                .add(CRIMSON_CAMPFIRE.block())
                .add(DARK_OAK_CAMPFIRE.block())
                .add(JUNGLE_CAMPFIRE.block())
                .add(MANGROVE_CAMPFIRE.block())
                .add(SPRUCE_CAMPFIRE.block())
                .add(WARPED_CAMPFIRE.block())
                .add(COBBLESTONE_CAMPFIRE.block())
                .add(ACACIA_SOUL_CAMPFIRE.block())
                .add(BIRCH_SOUL_CAMPFIRE.block())
                .add(CHERRY_SOUL_CAMPFIRE.block())
                .add(PALE_OAK_SOUL_CAMPFIRE.block())
                .add(CRIMSON_SOUL_CAMPFIRE.block())
                .add(DARK_OAK_SOUL_CAMPFIRE.block())
                .add(JUNGLE_SOUL_CAMPFIRE.block())
                .add(MANGROVE_SOUL_CAMPFIRE.block())
                .add(SPRUCE_SOUL_CAMPFIRE.block())
                .add(WARPED_SOUL_CAMPFIRE.block())
                .add(COBBLESTONE_SOUL_CAMPFIRE.block())
                .add(ACACIA_COPPER_CAMPFIRE.block())
                .add(BIRCH_COPPER_CAMPFIRE.block())
                .add(CHERRY_COPPER_CAMPFIRE.block())
                .add(PALE_OAK_COPPER_CAMPFIRE.block())
                .add(CRIMSON_COPPER_CAMPFIRE.block())
                .add(DARK_OAK_COPPER_CAMPFIRE.block())
                .add(JUNGLE_COPPER_CAMPFIRE.block())
                .add(MANGROVE_COPPER_CAMPFIRE.block())
                .add(OAK_COPPER_CAMPFIRE.block())
                .add(SPRUCE_COPPER_CAMPFIRE.block())
                .add(WARPED_COPPER_CAMPFIRE.block())
                .add(COBBLESTONE_COPPER_CAMPFIRE.block())
                .add(ACACIA_REDSTONE_CAMPFIRE.block())
                .add(BIRCH_REDSTONE_CAMPFIRE.block())
                .add(CHERRY_REDSTONE_CAMPFIRE.block())
                .add(PALE_OAK_REDSTONE_CAMPFIRE.block())
                .add(CRIMSON_REDSTONE_CAMPFIRE.block())
                .add(DARK_OAK_REDSTONE_CAMPFIRE.block())
                .add(JUNGLE_REDSTONE_CAMPFIRE.block())
                .add(MANGROVE_REDSTONE_CAMPFIRE.block())
                .add(OAK_REDSTONE_CAMPFIRE.block())
                .add(SPRUCE_REDSTONE_CAMPFIRE.block())
                .add(WARPED_REDSTONE_CAMPFIRE.block())
                .add(COBBLESTONE_REDSTONE_CAMPFIRE.block())
                .add(ACACIA_LAPIS_CAMPFIRE.block())
                .add(BIRCH_LAPIS_CAMPFIRE.block())
                .add(CHERRY_LAPIS_CAMPFIRE.block())
                .add(PALE_OAK_LAPIS_CAMPFIRE.block())
                .add(CRIMSON_LAPIS_CAMPFIRE.block())
                .add(DARK_OAK_LAPIS_CAMPFIRE.block())
                .add(JUNGLE_LAPIS_CAMPFIRE.block())
                .add(MANGROVE_LAPIS_CAMPFIRE.block())
                .add(OAK_LAPIS_CAMPFIRE.block())
                .add(SPRUCE_LAPIS_CAMPFIRE.block())
                .add(WARPED_LAPIS_CAMPFIRE.block())
                .add(COBBLESTONE_LAPIS_CAMPFIRE.block())
                .add(ACACIA_QUARTZ_CAMPFIRE.block())
                .add(BIRCH_QUARTZ_CAMPFIRE.block())
                .add(CHERRY_QUARTZ_CAMPFIRE.block())
                .add(PALE_OAK_QUARTZ_CAMPFIRE.block())
                .add(CRIMSON_QUARTZ_CAMPFIRE.block())
                .add(DARK_OAK_QUARTZ_CAMPFIRE.block())
                .add(JUNGLE_QUARTZ_CAMPFIRE.block())
                .add(MANGROVE_QUARTZ_CAMPFIRE.block())
                .add(OAK_QUARTZ_CAMPFIRE.block())
                .add(SPRUCE_QUARTZ_CAMPFIRE.block())
                .add(WARPED_QUARTZ_CAMPFIRE.block())
                .add(COBBLESTONE_QUARTZ_CAMPFIRE.block());
    }
}
